# Are inversions in repeat regions?
Now that we did some repeat modeling and classification, we can see if the breakpoints of any of the simulated inversions fall into these identified repeat regions.

In [28]:
library(dplyr)
library(tidyr)

In [29]:
repeats <- read.table("repeat.regions", header = T)
repeats <- repeats[order(repeats$contig), ]
head(repeats)

  contig position_start position_end
1 2L     11713984       11714447
2 2L     11714507       11715213
3 2L     11715209       11720435
4 2L     11720465       11720573
5 2L      1220606        1221069
6 2L      1221129        1221835
  class
1 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
2 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
3 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
4 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
5 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
6 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy

We'll to read in the inventory of all inversion positions and pull out the unique inversions. I really should have committed to either comma or tab separated tables.

In [30]:
inversions <- read.csv("../assess_called_sv/linkedread.sv.assessment", header = T)
inversions <- unique(inversions[, c(1,6,10,11)])
rownames(inversions) <- NULL
inversions$is_repeat <- as.character(NA)
head(inversions)
nrow(inversions)

  contig size  position_start position_end is_repeat
1 2L     small  3193196        3214221     NA
2 2L     small  3940211        3944863     NA
3 2L     small 13024404       13026577     NA
4 2L     small 14845709       14861200     NA
5 2L     small 20107901       20113695     NA
6 2R     small  4328632        4333509     NA

[1] 48

To do the matchy-matchy, we can borrow the fuzzy matching function we used to assess inversion calling. It will need some modifications to accommodate the slightly different use case.

In [31]:
for(i in 1:nrow(inversions)){
    .row <- inversions[i,]
    query <- which(
        repeats$contig == .row$contig &
        (repeats$position_start - 150 <= .row$position_start & repeats$position_end + 150 >= .row$position_start) |
        (repeats$position_start - 150 <= .row$position_end) & (repeats$position_end + 150 >= .row$position_end)
    )
    if(length(query) > 0) {
        inversions$is_repeat[i] <- do.call("paste", as.list(repeats$class[query]))
    }
}

In [32]:
are_repeats <- inversions[!is.na(inversions$is_repeat),]
are_repeats

   contig size   position_start position_end
1  2L     small   3193196        3214221
2  2L     small   3940211        3944863
5  2L     small  20107901       20113695
6  2R     small   4328632        4333509
16 3R     small  20006864       20010483
21 2L     medium  1591146        1776073
25 2R     medium  9640874        9978281
33 3R     medium 16760480       16905871
34 3R     medium 22722816       22831351
35 3R     medium 24237377       24380766
36 3R     medium 26216293       26389606
38 2L     large  18872129       20461266
41 3L     large    176550        2301734
   is_repeat
1  Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;LINE;Group-II;Group-2;R1-like;CR1-group;CR1
2  Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
5  Interspersed_Repeat;Transposable_Element;Class_II_DNA_Transposition;Transposase;CACTA;Transib Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Ty1-Copia
6  Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;LINE;Group-II;Group-2;R1-like;R1-group;I-group;Jockey Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
16 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
21 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy Interspersed_Repeat;Transposable_Element;Class_II_DNA_Transposition;Transposase;CACTA;Transib Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
25 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
33 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Bel-Pao
34 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
35 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;LINE;Group-II;Group-2;R1-like;R1-group;R1-subgroup;R1
36 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy
38 Interspersed_Repeat;Unknown
41 Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy Interspersed_Repeat;Transposable_Element;Class_I_Retrotransposition;Retrotransposon;Long_Terminal_Repeat_Element;Gypsy-ERV;Gypsy

Let's find which inversions had the most false negatives.

In [33]:
called_sv <- read.csv("../assess_called_sv/linkedread.sv.assessment", header = T)
false_neg <- filter(called_sv, assessment == "false negative") %>%
    group_by(contig, position_start, size) %>%
    summarize(n = length(depth)) %>%
    arrange(desc(n))
false_neg$is_repeat <- FALSE
head(false_neg, 20)

`summarise()` has grouped output by 'contig', 'position_start'. You can
override using the `.groups` argument.

   contig position_start size   n  is_repeat
1  2L      1591146       medium 55 FALSE
2  2L      6436329       medium 55 FALSE
3  2R      4328632       small  55 FALSE
4  3R     16760480       medium 40 FALSE
5  3R     26216293       medium 30 FALSE
6  2R      9640874       medium 26 FALSE
7  2R     17910285       medium 26 FALSE
8  2L       961650       xl     25 FALSE
9  2R     15862083       medium 25 FALSE
10 2R      6686007       xl     24 FALSE
11 2R      1439997       large  23 FALSE
12 2R     21284517       large  23 FALSE
13 2R     21736723       small  23 FALSE
14 2R     18236490       medium 22 FALSE
15 2L     13024404       small  21 FALSE
16 2R     10569437       small  21 FALSE
17 2L     20107901       small  20 FALSE
18 3L     21061086       medium 20 FALSE
19 3L     24140993       small  20 FALSE
20 3L     26678791       small  20 FALSE

We can now combine the inversions-in-repeats with the inversions-not-detected dataframe to see if there's a correlation of hard-to-call inversions being associated with repeat regions.

In [36]:
for(i in 1:nrow(false_neg)){
    .row <- false_neg[i,]
    query <- which(
        are_repeats$contig == .row$contig &
        are_repeats$position_start == .row$position_start
    )
    if(length(query) > 0) {
        false_neg$is_repeat[i] <- TRUE
    }
}
arrange(false_neg, desc(is_repeat))

   contig position_start size   n  is_repeat
1  2L      1591146       medium 55  TRUE
2  2R      4328632       small  55  TRUE
3  3R     16760480       medium 40  TRUE
4  3R     26216293       medium 30  TRUE
5  2R      9640874       medium 26  TRUE
6  2L     20107901       small  20  TRUE
7  2L      3940211       small  19  TRUE
8  2L     18872129       large  17  TRUE
9  3R     24237377       medium 17  TRUE
10 2L      3193196       small  15  TRUE
11 3R     20006864       small  15  TRUE
12 3R     22722816       medium 12  TRUE
13 3L       176550       large   3  TRUE
14 2L      6436329       medium 55 FALSE
15 2R     17910285       medium 26 FALSE
16 2L       961650       xl     25 FALSE
17 2R     15862083       medium 25 FALSE
18 2R      6686007       xl     24 FALSE
19 2R      1439997       large  23 FALSE
20 2R     21284517       large  23 FALSE
21 2R     21736723       small  23 FALSE
22 2R     18236490       medium 22 FALSE
23 2L     13024404       small  21 FALSE
24 2R     10569437       small  21 FALSE
25 3L     21061086       medium 20 FALSE
26 3L     24140993       small  20 FALSE
27 3L     26678791       small  20 FALSE
28 2L     11529165       large  19 FALSE
29 2R      9952840       small  19 FALSE
30 2R     11083686       small  19 FALSE
31 3R     22829883       small  19 FALSE
32 2L     17056243       medium 17 FALSE
33 3R     20081037       small  17 FALSE
34 2L     20404853       medium 16 FALSE
35 3L      5332918       xl     15 FALSE
36 3R      5316416       xl     15 FALSE
37 3R     21788248       large  15 FALSE
38 3R     19738053       large  14 FALSE
39 2L     14845709       small  13 FALSE
40 3R     24971985       small  10 FALSE
41 3R     25379867       small  10 FALSE
42 3L      9943175       medium  8 FALSE
43 3L      1700629       medium  6 FALSE
44 3L      4085868       small   6 FALSE
45 3L     17994845       small   6 FALSE
46 3L     14492093       small   5 FALSE
47 3L      6119288       medium  4 FALSE
48 3L     18163968       large   2 FALSE